### ISSUE TITLE
Duplicated links in JHU collect

### ISSUE THREAD

**Issue by sjiang417** [PMA-2020/collect#2]
Hi all,

I've noticed an issue of duplicated links across multiple observations in the same household. By "link" I'm referring to the link between HH and female forms. This issue has been noted in all WGE ODK forms. So far haven't been found in core FP. Posting some screenshots to show the problem as below.

Normally, we'd expect "link" to be generated randomly for different observations. Each female observation will have a unique link, which matches the link in hh member. So that later HH and female information can be merged without a problem. Below is a screenshot from FP data
![odk_link_normal](https://user-images.githubusercontent.com/34286460/43481894-2ec4b4b8-94d5-11e8-9002-83aad5f75164.JPG)

However, in WGE data, female observations from the same household has the same link, which causes problem later in data management. 
![odk_link_duplicate](https://user-images.githubusercontent.com/34286460/43481950-545a7dde-94d5-11e8-8a04-baa676bd6262.JPG)

"link" is an important variable that we use to clean duplicates and merge information from HHQ and FQ correctly. Can any one please take care of the problem? If not fixable in JHU collect, can any one report this issue to ODK collect?

Thanks,
Shulin

**Comment by joeflack4** [comment]
James discovered that the issue had to do with code that was written in the WGE form(s). It is not an issue with JHU Collect.

@jkpr Would you be able to reach out to Sam and let him know to fix this issue, should we use WGE in the future?

**Comment by jkpr** [comment]
@joeflack4 Shulin is sending that email.

**Comment by joeflack4** [comment]
Awesome. Closing this~
